apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: amazon1
  template:
    metadata:
      labels:
        app: amazon1
    spec:
      containers:
      - name: amazon1
        image: rajeshgadda/amazon:latest
        ports:
        - containerPort: 3000  # Port your application listens on
